### ISSUE TITLE
Typehole not picking up nulls

### ISSUE THREAD

**Issue by andrew-ironforge** [rikukissa/typehole#14] opened 2021-05-22 00:53 UTC
I've got a typehole as follows:

<img width="454" alt="Screen Shot 2021-05-21 at 7 51 50 PM" src="https://user-images.githubusercontent.com/29921020/119209733-fdf7a900-ba6d-11eb-9935-1d9451b584a1.png">

`row` is the following in the debugger:
<img width="419" alt="Screen Shot 2021-05-21 at 7 52 21 PM" src="https://user-images.githubusercontent.com/29921020/119209748-0fd94c00-ba6e-11eb-9ebc-63d87d78ddf9.png">

Notice how `totalCompensation` is `null` even though the typehole only picks up the string. I would expect the generated type to be `totalCompensation: string | null`;

I did run this typehole a number of times and it *should* have picked up the `null` value before I put a breakpoint here for a screenshot.

**Comment by rikukissa** [comment] 2021-05-22 07:41
Definitely seems like a bug. I wasn't able to reproduce it with 

```
const list = ["hello", null];

type AutoDiscovered = any;

list.forEach((val) => {
  console.log(typehole.t3<AutoDiscovered>(val));
});
```

and keep getting `null | string` as the output type. Can you verify you have the latest typehole runtime installed (1.6.0)?
I made some fixes earlier and it's possible that this would now be fixed

**Comment by rikukissa** [comment] 2021-05-22 07:45
I was able to reproduce it with 

```typescript
const list = ["hello", null, 2];

interface AutoDiscovered {
  hello?: number | string;
}

list.forEach((val, i) => {
  setTimeout(() => {
    console.log(typehole.t14<AutoDiscovered>({ hello: val }));
  }, 1000 * i);
});
```

I'll take a look at what's going on

**Comment by rikukissa** [comment] 2021-05-22 10:35
There also seems to be something off with how [json-to-ts](https://github.com/MariusAlch/json-to-ts) generates the types in case of `null`

With this input

```js
{ __typeholeRootWrapper__: [ { a: 2 }, { a: null } ] }
```

We get this output

```typescript
interface RootObject {
  __typeholeRootWrapper__: TypeholeRootWrapper[];
}
interface TypeholeRootWrapper {
  a?: number;
}
```

I'd expect it to be 

```typescript
interface RootObject {
  __typeholeRootWrapper__: TypeholeRootWrapper[];
}
interface TypeholeRootWrapper {
  a: number | null;
}
```

**Comment by andrew-ironforge** [comment] 2021-05-22 13:33
Yeah I wonder if these are related. Perhaps json-to-ts just doesn't handle nulls well

**Comment by rikukissa** [comment] 2021-05-22 16:27
I've now forked `json-to-ts` and fixed the null handling. The fix is available in release https://github.com/rikukissa/typehole/releases/tag/1.6.2 . See if upgrading the extension and the runtime package would fix this. I'll close this issue for now, but please reopen if it still happens

**Closed by rikukissa** 2021-05-22 16:27 UTC
